---
title: "Demo20180313"
author: "David Chiu"
date: "2018年3月13日"
output: html_document
---

## save & load
```{r}

#save.image("C:/Users/nc20/Desktop/0313.RData")
# get working directory
getwd()

# set working directory
setwd('C:/Users/nc20/Desktop/')

# save all variables into RData file
save.image("0313_2.RData")

# load variables from RData file
load("0313_2.RData")


```

## Save Model
```{r}
data(anscombe)
fit <- lm(y1 ~ x1, data = anscombe)
fit
plot(y1 ~ x1, data = anscombe)
abline(fit, col="red")
predict(fit, data.frame(x1 = 16))

save(fit, file = 'model.RData')
load('model.RData')

predict(fit, data.frame(x1 = 18))

```

## Homework1
```{r}
# use <- to assign variable
height <- 180
height <- c(180)

x <- c(1,2,3, 'hello')
# use class to examine data type
class(x)

# use c() to create vectors
names_vec  <- c('Brian', 'Toby', "Sherry")
height_vec <- c(180, 169, 173)
weight_vec <- c( 73,  87,  43)

# calculate bmi with a math formula
bmi_vec <- weight_vec / (height_vec / 100) ^ 2

# assign names to vector with names infix function
names(bmi_vec) <- names_vec

# filter vector with given condition
bmi_vec[bmi_vec < 18.5]
bmi_vec[bmi_vec >= 24]

# filter vector with & or | condition
result <- bmi_vec[(bmi_vec < 18.5) | (bmi_vec >= 24)]
names(result)


! ( (bmi_vec >= 18.5) & (bmi_vec < 24) )

bmi_vec[! ( (bmi_vec >= 18.5) & (bmi_vec < 24) )]

# use which to get filtering condition position
bmi_vec[which(! ( (bmi_vec >= 18.5) & (bmi_vec < 24) ))]
```

## Matrix
```{r}

# concatenate vector 
a <- c(1,2)
a <- c(a, 3)
a

b <- c(4,5)
d <- c(a,b)
d

# use vector to create matrix
kevin <- c(85, 73)
marry <- c(72, 64)
jerry <- c(59, 66)

c(kevin, marry, jerry)

matrix(c(kevin, marry, jerry), nrow = 3)
?matrix

matrix(c(kevin, marry, jerry), nrow = 3 ,byrow = TRUE)

# create matrix with byrow=FALSEand byrow=TRUE
1:9

matrix(1:9, ncol = 4, nrow = 4)

matrix(1:9, nrow = 3)
m <- matrix(1:9, nrow = 3, byrow = TRUE)

# filter matrix element by position
m[1,]
m[,1]
m[2,2]

# add column names and row names to matrix
mat <- matrix(c(kevin, marry, jerry), nrow = 3 ,byrow = TRUE)
mat

rownames(mat) <- c('kevin', 'marry', 'jerry')
mat

colnames(mat) <- c('first', 'second')
mat

mat['kevin',]
mat[,'first']
mat['marry', 'second']


mat <- matrix(c(kevin, marry, jerry), nrow = 3 ,byrow = TRUE, dimnames = list( c('kevin', 'marry', 'jerry') , c('first', 'second') ) )

# get basic info of a matrix
dim(mat)
nrow(mat)
ncol(mat)

# filter matrix by position, boolean and name
mat[1,]
mat[c(TRUE, FALSE, FALSE),]
mat['kevin',]

mat[,1]
mat[,c(TRUE, FALSE)]
mat[,'first']

mat[c(2,3),]
mat[2:3,]
mat[c(FALSE, TRUE, TRUE), ]
mat[c('marry', 'jerry'),]

mat[2,1]
mat['marry', 'first']

# row bind
mat2 <- rbind(mat, c(78, 63))
rownames(mat2)[4] <- 'sam'
mat2

# column bind
mat3 <- cbind(mat, c(82, 77, 70))
mat3
colnames(mat3)[3] 
colnames(mat3)[3] <- 'third'
mat3

# matrix computation
m1 <-matrix(1:4, byrow=TRUE, nrow=2)
m1

m2 <-matrix(5:8, byrow=TRUE, nrow=2)
m2

m1 + m2
m1 - m2
m1 * m2
m1 / m2

mat2
rowSums(mat2)
colSums(mat2)
?rowSums

# Product of matrix
m1  *  m2
m1 %*% m2

# 9 X 1
m1 <- matrix(1:9, nrow = 9)
m1

# 1 X 9 
m2 <- matrix(1:9, ncol = 9)
m2

# 9X1 %*% 1X9 = 9X9
m1 %*% m2



## Exercise
kevin <- c(85, 73)
marry <- c(72, 64)
jerry <- c(59, 66)
mat <- matrix(c(kevin, marry, jerry), nrow = 3, byrow=TRUE)


colnames(mat) <- c('first', 'second')
rownames(mat) <- c('kevin', 'marry', 'jerry')

# method 1
mat[,1] * 0.4 + mat[,2] * 0.6
mat[,'first'] * 0.4 + mat[,'second'] * 0.6

# method 2: 3X2 %*% 2X1 = 3X1
mat %*% matrix(c(0.4, 0.6), nrow = 2)

```


## Factor
```{r}

## create a vector
weather <- c('sunny', 'rainy', 'cloudy', 'rainy', 'cloudy')
weather
class(weather)

## create a factor from vector
weather_category <- factor(weather)
weather_category
class(weather_category)

##use levels to examine categories
levels(weather_category)


temperature <-c("Low", "High", "High", "Medium", "Low", "Medium")

# create an ordering factor
temperature_category <- factor(temperature, order=TRUE, levels=c("Low", "Medium", "High"))

temperature

temperature[2] > temperature[1]
temperature[1] > temperature[2]

temperature_category
temperature_category[3] > temperature_category[1]
temperature_category[4] > temperature_category[3]

levels(temperature_category)

# replace factor name with new name
temperature <-c("Low", "High", "High", "Medium", "Low", "Medium")
temperature_category <- factor(temperature)
temperature_category

levels(temperature_category)
levels(temperature_category) <- c('H', 'L', 'M')
temperature_category
```

## Data Frame
```{r}
days <-c('mon','tue', 'wed', 'thu','fri')
temp <-c(22.2 ,   21,    23,  24.3,   25)
rain <-c(TRUE , TRUE, FALSE, FALSE, TRUE)

class(days)
class(temp)
class(rain)

d <- c(days, temp, rain)
d
class(d)

mat <- matrix(c(days, temp, rain), nrow = 5)
class(mat)


df <- data.frame(days, temp, rain)
class(df)
View(df)

class(df)
str(df)
summary(df)


data()

## outbreaks dataset
### https://cran.r-project.org/web/packages/outbreaks/index.html
### http://www.repidemicsconsortium.org/

data(iris)
View(iris)
class(iris)

str(iris)
summary(iris)

head(iris)
head(iris, 10)

?head

tail(iris)
tail(iris, 10)

iris[1:3 , ]
iris[1:3 , 1]
iris[1:3 , 'Sepal.Length']
head(iris[    , 1:2])
iris[ 1:6   , 1:2]

str(iris)
head(iris$Sepal.Length)

five.sepal.iris <- iris[1:5, c('Sepal.Length', 'Sepal.Width')]

setosa.data <- iris[iris$Species == 'setosa', 1:5]
head(setosa.data)

which(iris$Species == 'setosa')

setosa.data2 <- iris[which(iris$Species == 'setosa'), 1:5]

head(sort(iris$Sepal.Length))
head(sort(iris$Sepal.Length, decreasing = TRUE))

a <- c(3,1,2,7,9,4)
# return ordered value
sort(a)

# return ordered index (position)
order(a)

head(iris[order(iris$Sepal.Length),])
head(iris[order(iris$Sepal.Length, decreasing = TRUE),])
```


